// src/main/java/com/edutech/center/application/service/AttendancePdfExportService.java
package com.edutech.center.application.service;

import com.edutech.center.application.dto.AttendanceBucket;
import com.edutech.center.application.dto.AttendancePeriodReport;
import com.edutech.center.application.dto.StudentBucketStat;
import com.lowagie.text.*;
import com.lowagie.text.pdf.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 * Generates a PDF attendance report using OpenPDF (LGPL).
 *
 * <p>Layout:
 * <ul>
 *   <li>Header: title + batch name + date range + period</li>
 *   <li>AI narration paragraph (generated by AttendanceReportService)</li>
 *   <li>Per-bucket section with student statistics table</li>
 *   <li>At-risk students summary box</li>
 *   <li>Footer: generated timestamp</li>
 * </ul>
 */
@Service
public class AttendancePdfExportService {

    private static final Logger log = LoggerFactory.getLogger(AttendancePdfExportService.class);

    // Colour palette
    private static final Color COLOR_HEADER_BG  = new Color(0x1A, 0x1A, 0x2E);
    private static final Color COLOR_CYAN        = new Color(0x22, 0xD3, 0xEE);
    private static final Color COLOR_GREEN       = new Color(0x10, 0xB9, 0x81);
    private static final Color COLOR_AMBER       = new Color(0xF5, 0x9E, 0x0B);
    private static final Color COLOR_RED         = new Color(0xEF, 0x44, 0x44);
    private static final Color COLOR_TABLE_EVEN  = new Color(0xF8, 0xFA, 0xFC);
    private static final Color COLOR_TABLE_HEAD  = new Color(0x1E, 0x3A, 0x5F);
    private static final Color COLOR_AT_RISK_BG  = new Color(0xFF, 0xF0, 0xF0);

    private static final Font FONT_TITLE    = new Font(Font.HELVETICA, 18, Font.BOLD,   new Color(0x22, 0xD3, 0xEE));
    private static final Font FONT_SUBTITLE = new Font(Font.HELVETICA, 11, Font.NORMAL, new Color(0x60, 0x7B, 0x8B));
    private static final Font FONT_SECTION  = new Font(Font.HELVETICA, 12, Font.BOLD,   new Color(0x1E, 0x3A, 0x5F));
    private static final Font FONT_BODY     = new Font(Font.HELVETICA,  9, Font.NORMAL, Color.DARK_GRAY);
    private static final Font FONT_TH       = new Font(Font.HELVETICA,  8, Font.BOLD,   Color.WHITE);
    private static final Font FONT_TD       = new Font(Font.HELVETICA,  8, Font.NORMAL, Color.DARK_GRAY);
    private static final Font FONT_TD_RISK  = new Font(Font.HELVETICA,  8, Font.BOLD,   COLOR_RED);
    private static final Font FONT_NARR     = new Font(Font.HELVETICA, 10, Font.ITALIC, new Color(0x37, 0x47, 0x51));
    private static final Font FONT_FOOTER   = new Font(Font.HELVETICA,  7, Font.NORMAL, Color.GRAY);

    /**
     * Generates the PDF bytes for the given report + AI narration.
     * @param report       computed period report
     * @param aiNarration  AI-generated narrative paragraph (may be rule-based fallback)
     * @return             raw PDF bytes
     */
    public byte[] generate(AttendancePeriodReport report, String aiNarration) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        Document doc = new Document(PageSize.A4, 40, 40, 60, 50);

        try {
            PdfWriter writer = PdfWriter.getInstance(doc, out);
            writer.setPageEvent(new PageFooter(report));
            doc.open();

            // ── Title block ──────────────────────────────────────────────────
            Paragraph title = new Paragraph("Attendance Report", FONT_TITLE);
            title.setSpacingAfter(4f);
            doc.add(title);

            doc.add(new Paragraph("Batch: " + report.batchName(), FONT_SUBTITLE));
            doc.add(new Paragraph("Period: " + report.period().name()
                    + "  |  " + report.from() + " \u2192 " + report.to(), FONT_SUBTITLE));
            doc.add(new Paragraph("At-Risk Students: " + report.atRiskStudentIds().size(), FONT_SUBTITLE));
            doc.add(Chunk.NEWLINE);

            // ── AI narration ────────────────────────────────────────────────
            if (aiNarration != null && !aiNarration.isBlank()) {
                PdfPTable narrativeBox = new PdfPTable(1);
                narrativeBox.setWidthPercentage(100);
                PdfPCell cell = new PdfPCell(new Paragraph(aiNarration, FONT_NARR));
                cell.setBorderColor(COLOR_CYAN);
                cell.setBorderWidth(1f);
                cell.setPadding(10f);
                cell.setBackgroundColor(new Color(0xF0, 0xFD, 0xFF));
                narrativeBox.addCell(cell);
                doc.add(narrativeBox);
                doc.add(Chunk.NEWLINE);
            }

            // ── Per-bucket sections ──────────────────────────────────────────
            for (AttendanceBucket bucket : report.buckets()) {
                // Bucket heading
                Paragraph bucketHead = new Paragraph(bucket.label(), FONT_SECTION);
                bucketHead.setSpacingBefore(12f);
                bucketHead.setSpacingAfter(4f);
                doc.add(bucketHead);

                doc.add(new Paragraph("Batch Average: " + bucket.batchAveragePercent() + "%  |  "
                        + bucket.from() + " \u2192 " + bucket.to(), FONT_SUBTITLE));
                doc.add(Chunk.NEWLINE);

                if (bucket.students().isEmpty()) {
                    doc.add(new Paragraph("No students in this batch.", FONT_BODY));
                    continue;
                }

                PdfPTable table = buildStudentTable(bucket);
                doc.add(table);
            }

            // ── At-risk summary ─────────────────────────────────────────────
            if (!report.atRiskStudentIds().isEmpty()) {
                doc.add(Chunk.NEWLINE);
                Paragraph atRiskHead = new Paragraph("\u26a0 Students Requiring Attention", FONT_SECTION);
                atRiskHead.setSpacingBefore(8f);
                atRiskHead.setSpacingAfter(4f);
                doc.add(atRiskHead);

                // Collect at-risk student names from last bucket (most recent data)
                if (!report.buckets().isEmpty()) {
                    AttendanceBucket lastBucket = report.buckets().get(report.buckets().size() - 1);
                    PdfPTable riskTable = new PdfPTable(3);
                    riskTable.setWidthPercentage(60);
                    riskTable.setWidths(new float[]{3f, 1.5f, 1.5f});
                    addTh(riskTable, "Student");
                    addTh(riskTable, "Attendance%");
                    addTh(riskTable, "Absences");
                    for (StudentBucketStat s : lastBucket.students()) {
                        if (s.atRisk()) {
                            addTdRisk(riskTable, s.studentName());
                            addTdRisk(riskTable, s.attendancePercent() + "%");
                            addTdRisk(riskTable, String.valueOf(s.absent()));
                        }
                    }
                    doc.add(riskTable);
                }
            }

            doc.close();
        } catch (Exception e) {
            log.error("PDF generation failed: {}", e.getMessage(), e);
            throw new RuntimeException("PDF generation failed", e);
        }

        return out.toByteArray();
    }

    // ─── Table builders ───────────────────────────────────────────────────────

    private PdfPTable buildStudentTable(AttendanceBucket bucket) throws DocumentException {
        PdfPTable table = new PdfPTable(9);
        table.setWidthPercentage(100);
        table.setWidths(new float[]{3f, 1f, 1f, 1f, 1f, 1f, 1.2f, 1.2f, 0.8f});

        // Header row
        String[] headers = {"Student", "Sessions", "Present", "Absent", "Late", "Excused", "Attend%", "Risk", "Streak"};
        for (String h : headers) addTh(table, h);

        // Data rows
        boolean evenRow = false;
        for (StudentBucketStat s : bucket.students()) {
            Color rowBg = evenRow ? COLOR_TABLE_EVEN : Color.WHITE;
            addTd(table, s.studentName(), rowBg, s.atRisk() ? FONT_TD_RISK : FONT_TD);
            addTd(table, String.valueOf(s.totalSessions()), rowBg, FONT_TD);
            addTdColored(table, String.valueOf(s.present()),  rowBg, COLOR_GREEN);
            addTdColored(table, String.valueOf(s.absent()),   rowBg, COLOR_RED);
            addTdColored(table, String.valueOf(s.late()),     rowBg, COLOR_AMBER);
            addTd(table, String.valueOf(s.excused()),         rowBg, FONT_TD);
            // % cell with color
            Color pctColor = s.attendancePercent().doubleValue() >= 85 ? COLOR_GREEN
                           : s.attendancePercent().doubleValue() >= 75 ? COLOR_AMBER : COLOR_RED;
            Font pctFont = new Font(Font.HELVETICA, 8, Font.BOLD, pctColor);
            addTd(table, s.attendancePercent() + "%", rowBg, pctFont);
            // Risk
            addTd(table, s.atRisk() ? "\u26a0 YES" : "OK", s.atRisk() ? COLOR_AT_RISK_BG : rowBg,
                  s.atRisk() ? FONT_TD_RISK : FONT_TD);
            // Streak
            addTd(table, s.streak() > 0 ? "\uD83D\uDD25" + s.streak() : "\u2014", rowBg, FONT_TD);
            evenRow = !evenRow;
        }
        return table;
    }

    private void addTh(PdfPTable table, String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text, FONT_TH));
        cell.setBackgroundColor(COLOR_TABLE_HEAD);
        cell.setPadding(5f);
        cell.setBorderWidth(0.5f);
        cell.setBorderColor(Color.LIGHT_GRAY);
        table.addCell(cell);
    }

    private void addTd(PdfPTable table, String text, Color bg, Font font) {
        PdfPCell cell = new PdfPCell(new Phrase(text, font));
        cell.setBackgroundColor(bg);
        cell.setPadding(4f);
        cell.setBorderWidth(0.3f);
        cell.setBorderColor(Color.LIGHT_GRAY);
        table.addCell(cell);
    }

    private void addTdColored(PdfPTable table, String text, Color bg, Color textColor) {
        addTd(table, text, bg, new Font(Font.HELVETICA, 8, Font.BOLD, textColor));
    }

    private void addTdRisk(PdfPTable table, String text) {
        addTd(table, text, COLOR_AT_RISK_BG, FONT_TD_RISK);
    }

    // ─── Page footer ──────────────────────────────────────────────────────────

    private static class PageFooter extends PdfPageEventHelper {
        private final AttendancePeriodReport report;
        PageFooter(AttendancePeriodReport report) { this.report = report; }

        @Override
        public void onEndPage(PdfWriter writer, Document document) {
            PdfContentByte cb = writer.getDirectContent();
            String footerText = "NexusEd Attendance Report  |  " + report.batchName()
                    + "  |  Generated: " + LocalDate.now().format(DateTimeFormatter.ISO_DATE)
                    + "  |  Page " + writer.getPageNumber();
            ColumnText.showTextAligned(cb, Element.ALIGN_CENTER,
                    new Phrase(footerText, FONT_FOOTER),
                    (document.left() + document.right()) / 2,
                    document.bottom() - 10, 0);
        }
    }
}
