apiVersion: v1
kind: Service
metadata:
  name: notification-svc
  namespace: edutech
  labels:
    app: notification-svc
    app.kubernetes.io/name: notification-svc
    app.kubernetes.io/part-of: edutech-platform
spec:
  selector:
    app: notification-svc
  ports:
    - name: http
      port: 8094
      targetPort: 8094
      protocol: TCP
  type: ClusterIP
