spring:
  application:
    name: ${PERFORMANCE_SVC_NAME}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${PERFORMANCE_SVC_DB_NAME}
    username: ${PERFORMANCE_SVC_DB_USERNAME}
    password: ${PERFORMANCE_SVC_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: performance_schema
  flyway:
    locations: classpath:db/migration/performance
    schemas: performance_schema
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${PERFORMANCE_SVC_KAFKA_GROUP_ID}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.edutech.*
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: ${PERFORMANCE_SVC_PORT}
  shutdown: graceful

kafka:
  topics:
    performance-events: ${KAFKA_TOPIC_PERFORMANCE_EVENTS}
    audit-immutable: ${KAFKA_TOPIC_AUDIT_IMMUTABLE}
    exam-events: ${KAFKA_TOPIC_EXAM_EVENTS}
    student-events: ${KAFKA_TOPIC_STUDENT_EVENTS}
  consumer:
    student-events-group-id: ${PERFORMANCE_SVC_STUDENT_EVENTS_GROUP_ID:performance-svc-student-events}
    exam-events-group-id: ${PERFORMANCE_SVC_EXAM_EVENTS_GROUP_ID:performance-svc-exam-events}

management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS}
  metrics:
    tags:
      application: ${PERFORMANCE_SVC_NAME}
      environment: ${APP_ENVIRONMENT}
  tracing:
    sampling:
      probability: ${OTEL_SAMPLING_PROBABILITY}

otel:
  exporter:
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}

logging:
  level:
    root: ${LOG_LEVEL_ROOT}
    com.edutech: ${LOG_LEVEL_APP}
