apiVersion: v1
kind: Service
metadata:
  name: mentor-svc
  namespace: {{ .Values.namespace }}
  labels:
    {{ include "edutech.labels" . | nindent 4 }}
    {{ include "edutech.selectorLabels" (dict "app" "mentor-svc") | nindent 4 }}
spec:
  selector:
    {{ include "edutech.selectorLabels" (dict "app" "mentor-svc") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.services.mentorSvc.port }}
      targetPort: {{ .Values.services.mentorSvc.port }}
      protocol: TCP
    - name: grpc
      port: {{ .Values.services.mentorSvc.grpcPort }}
      targetPort: {{ .Values.services.mentorSvc.grpcPort }}
      protocol: TCP
  type: ClusterIP
