apiVersion: v1
kind: Service
metadata:
  name: assess-svc
  namespace: edutech
  labels:
    app: assess-svc
    app.kubernetes.io/name: assess-svc
    app.kubernetes.io/part-of: edutech-platform
spec:
  selector:
    app: assess-svc
  ports:
    - name: http
      port: 8084
      targetPort: 8084
      protocol: TCP
    - name: grpc
      port: 9093
      targetPort: 9093
      protocol: TCP
  type: ClusterIP
