apiVersion: v1
kind: Service
metadata:
  name: exam-tracker-svc
  namespace: {{ .Values.namespace }}
  labels:
    {{ include "edutech.labels" . | nindent 4 }}
    {{ include "edutech.selectorLabels" (dict "app" "exam-tracker-svc") | nindent 4 }}
spec:
  selector:
    {{ include "edutech.selectorLabels" (dict "app" "exam-tracker-svc") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.services.examTrackerSvc.port }}
      targetPort: {{ .Values.services.examTrackerSvc.port }}
      protocol: TCP
  type: ClusterIP
