apiVersion: v1
kind: Service
metadata:
  name: performance-svc
  namespace: edutech
  labels:
    app: performance-svc
    app.kubernetes.io/name: performance-svc
    app.kubernetes.io/part-of: edutech-platform
spec:
  selector:
    app: performance-svc
  ports:
    - name: http
      port: 8092
      targetPort: 8092
      protocol: TCP
    - name: grpc
      port: 9094
      targetPort: 9094
      protocol: TCP
  type: ClusterIP
