apiVersion: v1
kind: Service
metadata:
  name: parent-svc
  namespace: {{ .Values.namespace }}
  labels:
    {{ include "edutech.labels" . | nindent 4 }}
    {{ include "edutech.selectorLabels" (dict "app" "parent-svc") | nindent 4 }}
spec:
  selector:
    {{ include "edutech.selectorLabels" (dict "app" "parent-svc") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.services.parentSvc.port }}
      targetPort: {{ .Values.services.parentSvc.port }}
      protocol: TCP
  type: ClusterIP
