server:
  port: ${MENTOR_SVC_PORT:8088}
spring:
  application:
    name: mentor-svc
  datasource:
    url: ${MENTOR_DB_URL:jdbc:postgresql://localhost:5432/edutech}
    username: ${MENTOR_DB_USER:edutech}
    password: ${MENTOR_DB_PASSWORD:edutech}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: mentor_schema
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    schemas: mentor_schema
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

kafka:
  topics:
    session-booked: mentor.session.booked
    session-completed: mentor.session.completed
    feedback-submitted: mentor.session.feedback

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
