server:
  port: ${MENTOR_SVC_PORT:8088}

spring:
  application:
    name: mentor-svc
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${MENTOR_DB_NAME}
    username: ${MENTOR_DB_USER}
    password: ${MENTOR_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: mentor_schema
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    schemas: mentor_schema
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: ${REDIS_SSL_ENABLED}

kafka:
  topics:
    session-booked: ${KAFKA_TOPIC_MENTOR_SESSION_BOOKED}
    session-completed: ${KAFKA_TOPIC_MENTOR_SESSION_COMPLETED}
    feedback-submitted: ${KAFKA_TOPIC_MENTOR_SESSION_FEEDBACK}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
