apiVersion: v1
kind: Service
metadata:
  name: career-oracle-svc
  namespace: edutech
  labels:
    app: career-oracle-svc
    app.kubernetes.io/name: career-oracle-svc
    app.kubernetes.io/part-of: edutech-platform
spec:
  selector:
    app: career-oracle-svc
  ports:
    - name: http
      port: 8087
      targetPort: 8087
      protocol: TCP
    - name: grpc
      port: 9097
      targetPort: 9097
      protocol: TCP
  type: ClusterIP
