server:
  port: ${CAREER_ORACLE_SVC_PORT:8087}

spring:
  application:
    name: career-oracle-svc
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${CAREER_ORACLE_DB_NAME}
    username: ${CAREER_ORACLE_DB_USER}
    password: ${CAREER_ORACLE_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: careeroracle_schema
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    schemas: careeroracle_schema
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: career-oracle-svc
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

kafka:
  topics:
    career-recommended: ${KAFKA_TOPIC_CAREER_ORACLE_RECOMMENDED}
    career-profile-created: ${KAFKA_TOPIC_CAREER_ORACLE_PROFILE_CREATED}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
