apiVersion: v1
kind: Service
metadata:
  name: parent-svc
  namespace: edutech
  labels:
    app: parent-svc
    app.kubernetes.io/name: parent-svc
    app.kubernetes.io/part-of: edutech-platform
spec:
  selector:
    app: parent-svc
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      protocol: TCP
  type: ClusterIP
