apiVersion: v1
kind: Service
metadata:
  name: exam-tracker-svc
  namespace: edutech
  labels:
    app: exam-tracker-svc
    app.kubernetes.io/name: exam-tracker-svc
    app.kubernetes.io/part-of: edutech-platform
spec:
  selector:
    app: exam-tracker-svc
  ports:
    - name: http
      port: 8091
      targetPort: 8091
      protocol: TCP
  type: ClusterIP
