apiVersion: v1
kind: Service
metadata:
  name: python-ai-svc
  namespace: edutech
  labels:
    app: python-ai-svc
    app.kubernetes.io/name: python-ai-svc
    app.kubernetes.io/part-of: edutech-platform
spec:
  selector:
    app: python-ai-svc
  ports:
    - name: http
      port: 8095
      targetPort: 8095
      protocol: TCP
  type: ClusterIP
