apiVersion: v1
kind: Service
metadata:
  name: assess-svc
  namespace: {{ .Values.namespace }}
  labels:
    {{ include "edutech.labels" . | nindent 4 }}
    {{ include "edutech.selectorLabels" (dict "app" "assess-svc") | nindent 4 }}
spec:
  selector:
    {{ include "edutech.selectorLabels" (dict "app" "assess-svc") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.services.assessSvc.port }}
      targetPort: {{ .Values.services.assessSvc.port }}
      protocol: TCP
    - name: grpc
      port: {{ .Values.services.assessSvc.grpcPort }}
      targetPort: {{ .Values.services.assessSvc.grpcPort }}
      protocol: TCP
  type: ClusterIP
