apiVersion: apps/v1
kind: Deployment
metadata:
  name: performance-svc
  namespace: {{ .Values.namespace }}
  labels:
    {{ include "edutech.labels" . | nindent 4 }}
    {{ include "edutech.selectorLabels" (dict "app" "performance-svc") | nindent 4 }}
spec:
  replicas: {{ .Values.services.performanceSvc.replicas }}
  selector:
    matchLabels:
      {{ include "edutech.selectorLabels" (dict "app" "performance-svc") | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "edutech.selectorLabels" (dict "app" "performance-svc") | nindent 8 }}
        app.kubernetes.io/part-of: edutech-platform
      annotations:
        {{ include "edutech.prometheusAnnotations" (dict "port" (toString .Values.services.performanceSvc.port)) | nindent 8 }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      securityContext:
        {{ include "edutech.podSecurityContext" . | nindent 8 }}
      {{ include "edutech.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: performance-svc
          image: {{ include "edutech.image" (dict "name" "performance-svc" "Values" .Values) }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.services.performanceSvc.port }}
              name: http
              protocol: TCP
            - containerPort: {{ .Values.services.performanceSvc.grpcPort }}
              name: grpc
              protocol: TCP
          {{ include "edutech.envFrom" . | nindent 10 }}
          env:
            - name: SERVER_PORT
              value: {{ .Values.services.performanceSvc.port | quote }}
            - name: PERFORMANCE_SVC_PORT
              value: {{ .Values.services.performanceSvc.port | quote }}
          {{ include "edutech.readinessProbe" (dict "port" .Values.services.performanceSvc.port) | nindent 10 }}
          {{ include "edutech.livenessProbe" (dict "port" .Values.services.performanceSvc.port) | nindent 10 }}
          resources:
            {{- toYaml .Values.services.performanceSvc.resources | nindent 12 }}
          securityContext:
            {{ include "edutech.containerSecurityContext" . | nindent 12 }}
